import { GoogleGenerativeAI } from '@google/generative-ai';
import { PlannerSchema } from '../schemas/planner.schema.js';
import type { PlannerType } from '../schemas/planner.schema.js';

export const generateWeeklyPlanner = async (extractedText: string): Promise<PlannerType> => {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error('GEMINI_API_KEY is not configured on the server');
  }

  const genAI = new GoogleGenerativeAI(apiKey);
  const model = genAI.getGenerativeModel({ 
    model: 'gemini-2.5-flash-lite', 
    generationConfig: { responseMimeType: 'application/json' } 
  });

  const prompt = `
    You are an expert study planner. The user has uploaded a PDF containing their semester subjects (ranked by priority from hard to easy) and their daily schedule/routine.
    
    Here is the extracted text from the PDF:
    """
    ${extractedText}
    """
    
    Based on this text, generate an efficient weekly study planner (Monday to Sunday).
    Allocate more time and the best focus periods to "hard" subjects, then "medium", then "easy".
    Also include their regular daily routine activities (like sleep, classes, meals) in the schedule.
    
    Return a JSON object that STRICTLY matches the following schema:
    {
      "weeklyPlan": [
        {
          "day": "Monday",
          "tasks": [
            {
              "timeBlock": "08:00 - 09:00",
              "activity": "Breakfast and Commute",
              "type": "routine"
            },
            {
              "timeBlock": "09:00 - 11:00",
              "activity": "Advanced Calculus (Hard Subject)",
              "type": "study",
              "priority": "hard"
            }
          ]
        }
      ],
      "notes": "Any tips or summary about the schedule."
    }
    
    Ensure you output ONLY valid JSON matching this structure.
  `;

  const result = await model.generateContent(prompt);
  const responseText = result.response.text();
  
  let plannerJson;
  try {
    plannerJson = JSON.parse(responseText);
  } catch (parseErr) {
    console.error('Failed to parse LLM response as JSON', responseText);
    throw new Error('Invalid JSON generated by AI');
  }
  
  return PlannerSchema.parse(plannerJson);
};
